version: '3'

services:
  db:
    image: postgres:12-alpine
    container_name: passtorage-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: passtorage
      POSTGRES_USER: passtorage
      POSTGRES_PASSWORD: passtorage
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - passtorage-db-data:/var/lib/postgresql/data

volumes:
  passtorage-db-data:
